export const ALL_PRODUCTS_CONSTANT_REQUEST = "ALL_PRODUCTS_CONSTANT_REQUEST";
export const ALL_PRODUCTS_CONSTANT_SUCCESS = "ALL_PRODUCTS_CONSTANT_SUCCESS";
export const ALL_PRODUCTS_CONSTANT_FAILURE = "ALL_PRODUCTS_CONSTANT_FAILURE";